version: "3.4"

services:
  agid-forms-frontend:
    image: agid-forms-frontend:local
    env_file:
      - .env
    build:
      context: .
      args:
        - HASURA_GRAPHQL_ENDPOINT
        - HASURA_GRAPHQL_ADMIN_SECRET
        - GATSBY_HASURA_GRAPHQL_ENDPOINT
        - GATSBY_BACKEND_ENDPOINT
        - GATSBY_UPLOAD_ENDPOINT
        - GOOGLE_ANALYTICS_TRACKING_ID
        - GATSBY_SENTRY_DSN
        - CORS
    labels:
      - traefik.enable=true
      - traefik.port=${HTTP_PORT}
      - traefik.frontend.rule=Host:${FRONTEND_HOST}
      - traefik.docker.network=app-tier
    ports:
      - "${HTTP_PORT}"
    networks:
      - app-tier
    restart: unless-stopped

networks:
  app-tier:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
