version: "3"

services:

  agid-forms-frontend:
    image: agid-forms-frontend:local
    env_file: 
      - .env
    build:
      context: .
      args:
        - HASURA_GRAPHQL_ENDPOINT
        - HASURA_GRAPHQL_ADMIN_SECRET
    ports:
      - "80"
    networks:
      - app-tier
    restart: unless-stopped

networks:
  app-tier:
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450
