export const GATSBY_HASURA_GRAPHQL_ENDPOINT =
  "https://graphql.danilospinelli.com/v1/graphql";

export const GATSBY_HASURA_TEST_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJydGQiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoicnRkIiwieC1oYXN1cmEtb3JnLWlkIjoiYWdpZCIsIngtaGFzdXJhLXVzZXItaWQiOiJkN2ZmN2FmNS01MWJhLTRmMDYtOWU5MS1hMDE0ZTA3Mjg3MWYifSwibmFtZSI6ImFsdmFyb0BhZ2lkLmdvdi5pdCIsImlhdCI6MTU1OTg5OTE1NywiZXhwIjoxNTYyNDkxMTU3fQ.ZoIvaAtyDxoX0qN9rxbogsprQAAR8QUZiNbbGpnzjOg";

export const GATSBY_BACKEND_ENDPOINT =
  "https://backend.danilospinelli.com/api/v1";
